<?php
/*****************
DEVELOPED BY @CreatorQsF
Code Generated By NextWith(Queeensya)
license:MIT
name:analyzeRss lib
*****************/
namespace analyzeRss;

class rssModel {
  private $title = "";
  private $date = "";
  private $description = "";
  private $body = "";
  private $url = "";
  public function setData($title, $date, $description, $body, $url) {
    $this->title = (string)filter_var($title);
    $this->date = (string)filter_var($date);
    $this->description = (string)filter_var($description);
    $this->body = (string)filter_var($body);
    $this->url = (string)filter_var($url);
  }
  public function getTitle() {
    return $this->title;
  }
  public function getDate() {
    return $this->date;
  }
  public function getDescription() {
    return $this->description;
  }
  public function getBody() {
    return $this->body;
  }
  public function getUrl() {
    return $this->url;
  }
}

class analyzeRss() extends rssModel {
  private $url;
  private $id;
  private $data;
  public function __construct($url, $date) {
    $this->url = (string)filter_var($url);
    $this->id = (string)filter_var($date);
  }
  private function setData() {

  }
  private function analyzeUrl() {
    $tmp = simplexml_load_file($this->url);
  }
  private function analyzeRssTwoPointZero($rss) {
    $data = array();
    foreach ($rss->channel->item as $item) {
      $x = array();
      $x['link'] = (string)$item->link;
      $x['title'] = (string)$item->title;
      $x['description'] = (string)$item->description;
      $x['pubDate'] = (string)$item->pubDate;
      $data[] = $x;
    }
    var_dump($data);
  }
  private function analyzeRssOnePointZero() {

  }
  private function analyzeRssAtom() {

  }
}
